spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.197:8848   #docker环境的nacos
    sentinel:
      transport:
        dashboard: 192.168.0.197:8849

dubbo:
  scan:
    base-packages: com.gk.cloud.alibaba.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.0.197
    port: 8848

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true